export const GET_MEDICAL_SUCCESS = "GET_MEDICAL_SUCCESS";
export const GET_MEDICAL_FAILURE = "GET_MEDICAL_FAILURE";

export const DELETE_MEDICAL_SUCCESS = "DELETE_MEDICAL_SUCCESS";
export const DELETE_MEDICAL_FAILURE = "DELETE_MEDICAL_FAILURE";

export const ADD_MEDICAL_SUCCESS = "ADD_MEDICAL_SUCCESS";
export const ADD_MEDICAL_FAILURE = "ADD_MEDICAL_FAILURE"

export const UPDATE_MEDICAL_SUCCESS = "UPDATE_MEDICAL_SUCCESS";
export const UPDATE_MEDICAL_FAILURE = "UPDATE_MEDICAL_FAILURE";