export const GET_SPECIALIZATION_SUCCESS = "GET_SPECIALIZATION_SUCCESS";
export const GET_SPECIALIZATION_FAILURE = "GET_SPECIALIZATION_FAILURE";

export const ADD_SPECIALIZATION_SUCCESS = "ADD_SPECIALIZATION_SUCCESS";
export const ADD_SPECIALIZATION_FAILURE = "ADD_SPECIALIZATION_FAILURE";

export const UPDATE_SPECIALIZATION_SUCCESS = "UPDATE_SPECIALIZATION_SUCCESS";
export const UPDATE_SPECIALIZATION_FAILURE = "UPDATE_SPECIALIZATION_FAILURE";

export const DELETE_SPECIALIZATION_SUCCESS = "DELETE_SPECIALIZATION_SUCCESS";
export const DELETE_SPECIALIZATION_FAILURE = "DELETE_SPECIALIZATION_FAILURE";