export const GET_PATIENT_SUCCESS = "GET_PATIENT_SUCCESS";
export const GET_PATIENT_FAILURE = "GET_PATIENT_FAILURE";

export const GET_PATIENT_ID_SUCCESS = "GET_PATIENT_ID_SUCCESS";
export const GET_PATIENT_ID_FAILURE = "GET_PATIENT_ID_FAILURE";

export const DELETE_PATIENT_SUCCESS = "DELETE_PATIENT_SUCCESS";
export const DELETE_PATIENT_FAILURE = "DELETE_PATIENT_FAILURE";

export const ADD_PATIENT_SUCCESS = "ADD_PATIENT_SUCCESS";
export const ADD_PATIENT_FAILURE = "ADD_PATIENT_FAILURE";

export const UPDATE_PATIENT_SUCCESS = "UPDATE_PATIENT_SUCCESS";
export const UPDATE_PATIENT_FAILURE = "UPDATE_PATIENT_FAILURE";
