export const GET_PHARMACIST_SUCCESS = "GET_PHARMACIST_SUCCESS";
export const GET_PHARMACIST_FAILURE = "GET_PHARMACIST_FAILURE";

export const ADD_PHARMACIST_SUCCESS = "ADD_PHARMACIST_SUCCESS";
export const ADD_PHARMACIST_FAILURE = "ADD_PHARMACIST_FAILURE";

export const UPDATE_PHARMACIST_SUCCESS = "UPDATE_PHARMACIST_SUCCESS";
export const UPDATE_PHARMACIST_FAILURE = "UPDATE_PHARMACIST_FAILURE";

export const DELETE_PHARMACIST_SUCCESS = "DELETE_PHARMACIST_SUCCESS";
export const DELETE_PHARMACIST_FAILURE = "DELETE_PHARMACIST_FAILURE";